PREFIX ds: 	<https://data.cityofnewyork.us/resource/kcdd-kkxy/>
PREFIX dsbase:  <https://data.cityofnewyork.us/resource/>
PREFIX geo: <http://www.w3.org/2003/01/geo/wgs84_pos#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

SELECT ?result WHERE {
  ?result a dsbase:kcdd-kkxy .
  ?result ds:longitude ?long .
  ?result ds:latitude ?lat .
  FILTER (xsd:float(?lat) > xsd:float(30) && xsd:float(?lat) < xsd:float(50) && xsd:float(?long) > xsd:float(-83) && xsd:float(?long) < xsd:float(-63))
}
